esphome:
  name: bed-sensor
  friendly_name: Датчик кровати
  on_boot: # Калибруем датчики при загрузке
    priority: 200
    then:
      - lambda: |-
          delay(2000);  // ждём стабилизации ADC
          float zero_r = id(bed_sensor_right).state;
          float zero_l = id(bed_sensor_left).state;
          id(right_threshold_on).make_call().set_value(zero_r + 0.07).perform();
          id(right_threshold_off).make_call().set_value(zero_r + 0.03).perform();
          id(left_threshold_on).make_call().set_value(zero_l + 0.07).perform();
          id(left_threshold_off).make_call().set_value(zero_l + 0.03).perform();

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# Home Assistant API
api:
  encryption:
    key: "***" # Ваш ключ шифрования

ota:
  - platform: esphome
    password: "***" # Ваш пароль OTA

network:
  enable_ipv6: true

openthread:
  device_type: FTD
  tlv: !secret thread_tlv # Ваш TLV ключ от сети Thread

# Испольщуем пины с поддержкой ADC (У меня ESP32C6)
substitutions:
  sensor_right: GPIO1
  sensor_left: GPIO6

sensor:
    # Изменение напряжения с правого датчика
  - platform: adc
    pin: $sensor_right
    id: bed_sensor_right
    attenuation: 12db
    update_interval: 100ms
    samples: 4
    filters:
      - median:
          window_size: 3
          send_every: 1
      - throttle: 200ms
    internal: true

    # Измерение напряжения с левого датчика
  - platform: adc
    pin: $sensor_left
    id: bed_sensor_left
    attenuation: 12db
    update_interval: 100ms
    samples: 4
    filters:
      - median:
          window_size: 3
          send_every: 1
      - throttle: 200ms
    internal: true

 # Сглаженный сенсор для отображения в Home Assistant
  - platform: template
    name: "Правый Напряжение"
    id: bed_sensor_right_smooth
    lambda: return id(bed_sensor_right).state;
    update_interval: 1s
    filters:
      - sliding_window_moving_average:
          window_size: 30
          send_every: 15
      - delta: 0.005
    unit_of_measurement: V
    accuracy_decimals: 3

  - platform: template
    name: "Левый Напряжение"
    id: bed_sensor_left_smooth
    lambda: return id(bed_sensor_left).state;
    update_interval: 1s
    filters:
      - sliding_window_moving_average:
          window_size: 30
          send_every: 15
      - delta: 0.005
    unit_of_measurement: V
    accuracy_decimals: 3

# Настройки порогов
number:
  - platform: template
    name: "Правый Порог ВКЛ"
    id: right_threshold_on
    mode: box
    optimistic: true
    restore_value: true
    min_value: 0
    max_value: 2.0
    step: 0.001
    unit_of_measurement: V

  - platform: template
    name: "Правый Порог ВЫКЛ"
    id: right_threshold_off
    mode: box
    optimistic: true
    restore_value: true
    min_value: 0
    max_value: 2.0
    step: 0.001
    unit_of_measurement: V

  - platform: template
    name: "Левый Порог ВКЛ"
    id: left_threshold_on
    mode: BOX
    optimistic: true
    restore_value: true
    min_value: 0
    max_value: 2.0
    step: 0.001
    unit_of_measurement: V

  - platform: template
    name: "Левый Порог ВЫКЛ"
    id: left_threshold_off
    mode: BOX
    optimistic: true
    restore_value: true
    min_value: 0
    max_value: 2.0
    step: 0.001
    unit_of_measurement: V

  - platform: template
    name: "Задержка включения" # Общая для обеих датчиков
    id: on_delay
    mode: BOX
    optimistic: True
    restore_value: True
    min_value: 0.1
    max_value: 2.0
    step: 0.1
    unit_of_measurement: сек

  - platform: template
    name: "Задержка выключения" # Общая для обеих датчиков
    id: off_delay
    mode: BOX
    optimistic: True
    restore_value: True
    min_value: 1
    max_value: 60
    step: 1
    unit_of_measurement: мин

# Бинарные сенсоры
binary_sensor:
  - platform: template
    name: "Правый"
    id: right_side_raw
    lambda: |-
      static bool state = false;
      float val = id(bed_sensor_right_smooth).state;  // <-- используем сглаженное (можно заменить на значение без фильтрации - "bed_sensor_right")
      if (!state && val > id(right_threshold_on).state) {
        state = true;
      } else if (state && val < id(right_threshold_off).state) {
        state = false;
      }
      return state;
    filters:
      - delayed_on: !lambda 'return id(on_delay).state * 1000;'
      - delayed_off: !lambda 'return id(off_delay).state * 60 * 1000;'

  - platform: template
    name: "Левый"
    id: left_side_raw
    lambda: |-
      static bool state = false;
      float val = id(bed_sensor_left_smooth).state;  // <-- используем сглаженное (можно заменить на значение без фильтрации - "bed_sensor_left")
      if (!state && val > id(left_threshold_on).state) {
        state = true;
      } else if (state && val < id(left_threshold_off).state) {
        state = false;
      }
       return state;
    filters:
      - delayed_on: !lambda 'return id(on_delay).state * 1000;'
      - delayed_off: !lambda 'return id(off_delay).state * 60 * 1000;'
